export const questionData = [
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 21434,
    unit: 2,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 7434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 4434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 6434,
    unit: 4,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 34,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 1434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3404,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3404,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 4,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 134,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 34312,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
  {
    datePublished: '12-03-2021',
    title: 'How do you turn it around when you fail to turn the user?',
    description:
      'Professor Emeka Chucks of Delta State Business School contrasts traditional approaches to branding - where brands are a visual identity and a promise to customers - to brands...',
    likeCount: 24,
    repliesCount: 42,
    lectureTitle: 'Lecture 12',
    duration: 3434,
    unit: 3,
  },
];

export const liveSessionData = [
  {
    date: '1-May-mon',
    startTime: '2:30 pm',
    endTime: '3:00 pm',
    title: 'Mockup class session',
    instructor: 'Prof Emeka Chuks',
  },
  {
    date: '1-May-mon',
    startTime: '2:30 pm',
    endTime: '3:00 pm',
    title: 'Mockup class session',
    instructor: 'Prof Emeka Chuks',
  },
  {
    date: '1-May-mon',
    startTime: '2:30 pm',
    endTime: '3:00 pm',
    title: 'Mockup class session',
    instructor: 'Prof Emeka Chuks',
  },
  {
    date: '2-Jun-mon',
    startTime: '2:30 pm',
    endTime: '3:00 pm',
    title: 'Mockup class session',
    instructor: 'Prof Emeka Chuks',
  },
  {
    date: '2-Jun-mon',
    startTime: '2:30 pm',
    endTime: '3:00 pm',
    title: 'Mockup class session',
    instructor: 'Prof Emeka Chuks',
  },
  {
    date: '3-Aug-mon',
    startTime: '2:30 pm',
    endTime: '3:00 pm',
    title: 'Mockup class session',
    instructor: 'Prof Emeka Chuks',
  },
  {
    date: '1-Aug-mon',
    startTime: '2:30 pm',
    endTime: '3:00 pm',
    title: 'Mockup class session',
    instructor: 'Prof Emeka Chuks',
  },
];

export const mockNotifications = [
  {
    action: 'New  school has been created',
    id: new Date().getTime(),
    name: 'Modupe Adeyemo',
    createdAt: '2021-07-28T20:45:49.582783+00:00',
    isRead: false,
  },
  {
    action: 'Announcements was created on the platform ',
    id: new Date().getTime(),
    name: 'Udochi',
    createdAt: '2021-06-29T21:45:49.582783+00:00',
    isRead: false,
  },
  {
    action: 'Delta State University has been edited',
    id: new Date().getTime(),
    name: 'Alex Adeshina',
    createdAt: '2021-07-29T10:46:48.162197+00:00',
    isRead: true,
  },
  {
    action: 'Delta State University has been edited',
    id: new Date().getTime(),
    name: 'Hebraheem',
    createdAt: '2021-07-28T21:45:49.582783+00:00',
    isRead: false,
  },
  {
    action: 'App was rebuild',
    id: new Date().getTime(),
    name: 'Gbenga',
    createdAt: '2021-07-26T10:46:48.162197+00:00',
    isRead: true,
  },
  {
    action: 'Fixed issue with library',
    id: new Date().getTime(),
    name: 'Chioma',
    createdAt: '2021-08-03T12:45:49.582783+01:00',
    isRead: true,
  },
  {
    action: 'Fixed issue with library',
    id: new Date().getTime(),
    name: 'Chioma',
    createdAt: '2021-08-02T11:45:49.582783+00:00',
    isRead: true,
  },
  {
    action: 'Fixed issue with library',
    id: new Date().getTime(),
    name: 'Chioma',
    createdAt: '2021-08-03T13:44:49.582783+01:00',
    isRead: true,
  },
  {
    action: 'Fixed issue with library',
    id: new Date().getTime(),
    name: 'Chioma',
    createdAt: '2021-08-05T13:46:49.582783+01:00',
    isRead: true,
  },
];
